#!/bin/bash

echo -n "Enter your birth day (e.g., Mar 18 2021)> "
read target_date

today=$(($(date --utc +%s)/86400))
target=$(($(date --utc --date "$target_date" +%s)/86400))
days=$(expr $today - $target)

echo ""
echo ""
echo "You've lived $days days (in other words $(($days/7)) weeks) so far."
echo ""
echo ""
echo ""
echo ""
echo "wait for the next activity"
sleep 7
# # It selects a random number and compare you choice with that \
# # random number until you find it.

NUMGUESS=0

echo "Guess a number between 1 and 20"

(( secret = RANDOM % 20 + 1 ))

while [[ guess -ne secret ]]
do
(( NUMGUESS = NUMGUESS + 1 ))
read -p "Enter guess: " guess

if (( guess < $secret )); then
    echo "Try higher..."
elif (( $guess > $secret )); then
    echo "Try lower..."
fi
done

printf "Yes! You guessed it in $NUMGUESS guesses.\n"

echo ""
echo ""
echo ""
echo ""

echo "wait for the next activity"
sleep 7

read -p "enter your annual salary: " $salary
read -p "enter your annual expenses: " $expenses
if [[ $salary -le $expenses ]]; then
    echo "I am sorry for you. You are not in a good position. May God Help You!"
    echo ""
    echo ""
else
    echo "Congratulations! You are getting rich :) "
    echo ""
    echo ""
fi